### ISSUE TITLE
Accessing search authors page produces a fatal error

### ISSUE THREAD

**Issue by Vitaliy-1** [pkp/classic#90]
**Describe the bug**
Visiting searchAuthors page produces a fatal error:
```
[Fri Jan  8 15:39:00 2021] 127.0.0.1:48808 [500]: GET /index.php/publicknowledge/search/authors - Uncaught Exception: DAOResultFactory instances do not support wasEmpty (DAO AuthorDAO)! in /home/doc/OJS/development/ojs/lib/pkp/classes/db/DAOResultFactory.inc.php:154
Stack trace:
#0 /home/doc/OJS/development/ojs/cache/t_compile/b4bc7db39b8c69690e4088d87370de4259f46a3d^c2055d14f27582f3361894f4184ce1a4c0497385_0.app.frontendpagessearchAuthor.php(98): DAOResultFactory->wasEmpty()
#1 /home/doc/OJS/development/ojs/lib/pkp/lib/vendor/smarty/smarty/libs/sysplugins/smarty_template_resource_base.php(123): content_5ff860740e0c09_87521700()
#2 /home/doc/OJS/development/ojs/lib/pkp/lib/vendor/smarty/smarty/libs/sysplugins/smarty_template_compiled.php(114): Smarty_Template_Resource_Base->getRenderedTemplateCode()
#3 /home/doc/OJS/development/ojs/lib/pkp/lib/vendor/smarty/smarty/libs/sysplugins/smarty_internal_template.php(216): Smarty_Template_Compiled->render()
#4 /home/doc/OJS/development/ojs/lib/pkp/lib/vendor/smarty/smarty/libs/sysplugins/smarty_internal_templatebase.php(232): Smarty_Internal_Template->render()
#5  in /home/doc/OJS/development/ojs/lib/pkp/classes/db/DAOResultFactory.inc.php on line 154
```

**Comment by asmecher** [comment]
This appears to affect OJS generally, not just the Classic theme. Transferring to pkp-lib...
